# Generated by Django 5.1.2 on 2024-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Id_Producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Precio', models.PositiveSmallIntegerField()),
                ('Marca', models.CharField(max_length=100)),
                ('Calidad', models.CharField(max_length=100)),
                ('Recibido', models.CharField(max_length=100)),
                ('Proovedor', models.CharField(max_length=100)),
                ('Cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
